version: "2"

run:
  timeout: 5m
  allow-parallel-runners: true
  tests: false

linters:
  default: none
  enable:
    - errcheck
    - ginkgolinter
    - goconst
    - govet
    - ineffassign
    - misspell
    - nakedret
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    revive:
      rules:
        - name: comment-spacings
        - name: indent-error-flow
        - name: superfluous-else
        - name: package-comments
        - name: exported
          disabled: true
        - name: unused-parameter
          disabled: true
        - name: var-naming
          disabled: true
  exclusions:
    rules:
      - linters:
          - staticcheck
        text: "SA1019"

formatters:
  enable:
    - gofmt
    - goimports
