# SPDX-FileCopyrightText: 2025 2025 INDUSTRIA DE DISEÑO TEXTIL S.A. (INDITEX S.A.)
# SPDX-FileContributor: enriqueavi@inditex.com
#
# SPDX-License-Identifier: Apache-2.0

{{ if $.Values.createnamespace }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $.Values.namespace }}
{{ end }}
