apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "overcommit.inditex.dev/v1alphav1",
          "kind": "Overcommit",
          "metadata": {
            "labels": {
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "k8s-overcommit"
            },
            "name": "overcommit-sample"
          },
          "spec": null
        },
        {
          "apiVersion": "overcommit.inditex.dev/v1alphav1",
          "kind": "OvercommitClass",
          "metadata": {
            "labels": {
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "k8s-overcommit"
            },
            "name": "overcommitclass-sample"
          },
          "spec": null
        }
      ]
    capabilities: Basic Install
    createdAt: "2025-06-30T14:24:32Z"
    operators.operatorframework.io/builder: operator-sdk-v1.39.2
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
  name: k8s-overcommit.v1.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: OvercommitClass
      name: overcommitclasses.overcommit.inditex.dev
      version: v1alphav1
    - kind: Overcommit
      name: overcommits.overcommit.inditex.dev
      version: v1alphav1
    required:
    - description: Certificate resource from cert-manager
      displayName: Certificate
      kind: Certificate
      name: certificates.cert-manager.io
      version: v1
    - description: Issuer resource from cert-manager
      displayName: Issuer
      kind: Issuer
      name: issuers.cert-manager.io
      version: v1
  description: Operator for make overcommit to pods based in classes
  displayName: k8s-overcommit-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - ""
          resources:
          - services
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - admissionregistration.k8s.io
          resources:
          - mutatingwebhookconfigurations
          - validatingwebhookconfigurations
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - replicasets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - cert-manager.io
          resources:
          - certificates
          - issuers
          verbs:
          - create
          - delete
          - get
          - list
          - update
          - watch
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - overcommit.inditex.dev
          resources:
          - overcommitclasses
          - overcommits
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - overcommit.inditex.dev
          resources:
          - overcommitclasses/finalizers
          - overcommits/finalizers
          verbs:
          - update
        - apiGroups:
          - overcommit.inditex.dev
          resources:
          - overcommitclasses/status
          - overcommits/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: k8s-overcommit-controller-manager
      deployments:
      - label:
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: k8s-overcommit
          control-plane: controller-manager
        name: k8s-overcommit-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - -metrics-secure=false
                - --metrics-bind-address=:8080
                command:
                - /manager
                env:
                - name: ENABLE_OVERCOMMIT_CONTROLLER
                  value: "true"
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: POD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                image: ghcr.io/inditextech/k8s-overcommit-operator:1.0.0
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                ports:
                - containerPort: 8080
                  name: metrics
                  protocol: TCP
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: k8s-overcommit-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: k8s-overcommit-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - ocp
  - k8s
  - overcommit
  links:
  - name: K8s Overcommit
    url: https://k8s-overcommit.domain
  maintainers:
  - email: enriqueavi@inditex.com
    name: enriqueAndresVillar
  maturity: alpha
  minKubeVersion: 1.22.0
  provider:
    name: inditexTech
  version: 1.0.0
