# permissions for end users to edit overcommits.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8s-overcommit
    app.kubernetes.io/managed-by: kustomize
  name: overcommit-editor-role
rules:
- apiGroups:
  - overcommit.inditex.dev
  resources:
  - overcommits
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - overcommit.inditex.dev
  resources:
  - overcommits/status
  verbs:
  - get
