apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: k8s-overcommit.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: OvercommitClass is the Schema for the overcommitclasses API
      displayName: Overcommit Class
      kind: OvercommitClass
      name: overcommitclasses.overcommit.inditex.dev
      version: v1
    - description: Overcommit is the Schema for the overcommits API
      displayName: Overcommit
      kind: Overcommit
      name: overcommits.overcommit.inditex.dev
      version: v1
    required:
    - description: Certificate resource from cert-manager
      displayName: Certificate
      kind: Certificate
      name: certificates.cert-manager.io
      version: v1
    - description: Issuer resource from cert-manager
      displayName: Issuer
      kind: Issuer
      name: issuers.cert-manager.io
      version: v1
  description: Operator for make overcommit to pods based in classes
  displayName: k8s-overcommit-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - ocp
  - k8s
  - overcommit
  links:
  - name: K8s Overcommit
    url: https://k8s-overcommit.domain
  maintainers:
  - email: enriqueavi@inditex.com
    name: enriqueAndresVillar
  maturity: alpha
  minKubeVersion: 1.22.0
  provider:
    name: inditexTech
  version: 0.0.0
