# SPDX-FileCopyrightText: 2025 2025 INDUSTRIA DE DISEÑO TEXTIL S.A. (INDITEX S.A.)
# SPDX-FileContributor: enriqueavi@inditex.com
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-overcommit-clusterrole
rules:
  - apiGroups:
    - '*'
    resources:
    - '*'
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    resources:
    - events
    verbs:
    - create
    - patch
    - update
  - apiGroups:
    - ""
    resources:
    - services
    - namespaces
    verbs:
    - create
    - get
    - list
    - watch
    - delete
    - update
    - patch
  - apiGroups:
    - admissionregistration.k8s.io
    resources:
    - mutatingwebhookconfigurations
    - validatingwebhookconfigurations
    verbs:
    - create
    - get
    - list
    - watch
    - delete
    - update
    - patch
  - apiGroups:
    - apps
    resources:
    - deployments
    - replicasets
    verbs:
    - create
    - get
    - list
    - delete
    - update
    - watch
    - update
  - apiGroups:
    - cert-manager.io
    resources:
    - certificates
    - issuers
    verbs:
    - create
    - delete
    - get
    - list
    - update
    - watch
  - apiGroups:
    - overcommit.inditex.dev
    resources:
    - "*"
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - "coordination.k8s.io"
    resources:
    - leases
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mutating-k8s-overcommit-binding
subjects:
  - kind: ServiceAccount
    name: {{ $.Values.serviceAccount.name }}
    namespace: {{ $.Values.namespace }}
roleRef:
  kind: ClusterRole
  name: k8s-overcommit-clusterrole
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-overcommit-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    name: {{ $.Values.serviceAccount.name }}
    namespace: {{ $.Values.namespace }}