name: Check Code Generation 🧪
on:
    pull_request:
jobs:
  check-dependencies-gen:
    name: Check Go Modules
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🧲
        uses: actions/checkout@v4

      - name: Setup Go ⬇️
        uses: actions/setup-go@v3
        with:
          go-version: 1.24.2

      - name: Check dependencies Generation 🧪
        run: |
            go mod tidy
            git diff  --ignore-matching-lines='.*createdAt:.*' --exit-code

  check-code-gen:
    name: Check SDK Code Generation 🧪
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🧲
        uses: actions/checkout@v4

      - name: Setup Go ⬇️
        uses: actions/setup-go@v3
        with:
          go-version: 1.24.2

      - name: Check dependencies Generation 🧪
        run: |
            make generate manifests bundle
            git diff  --ignore-matching-lines='.*createdAt:.*' --exit-code
