name: ⚒️ Go tests and linting for the webhook
on:
  pull_request:
jobs:
  test:
    name: Test 🔨
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 🧲
      uses: actions/checkout@v4

    - name: Restore go build cache ⏬
      uses: actions/cache@v4
      with:
        path: ~/.cache/go-build
        key: ${{ runner.os }}-go-build-v1

    - name: Setup Go ⬇️
      uses: actions/setup-go@v3
      with:
        go-version: 1.24.2

    - name: Build and test 🏗️
      run: |
        make build
        make test

  lint:
    name: Lint 🔍
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 🧲
      uses: actions/checkout@v4

    - name: Restore go build cache ⏬
      uses: actions/cache@v4
      with:
        path: ~/.cache/go-build
        key: ${{ runner.os }}-go-build-v1

    - name: Setup Go ⬇️
      uses: actions/setup-go@v3
      with:
        go-version: 1.24.2

    - name: Linter 🔍
      run: |
        make lint
