name: ⚒️ Test Operator Bundle

on:
  pull_request:
jobs:
  test-bundle:
    name: Verify Operator Bundle
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.2"

      # Make the bundle
      - name: Make bundle
        run: |
            make generate manifests
            make bundle IMG=test.io/k8s-overcommit-operator/operator:test

      # Make the bundle image
      - name: Make bundle image
        run: make bundle-build BUNDLE_IMG=test.io/k8s-overcommit-operator/bundle:test